#!/usr/bin/env bash

# Safety first
set -o errexit -o pipefail -o nounset
# Change into the project's directory
cd "$(dirname "$0")/.."

poetry run black ./app ./tests ./scripts
poetry run ruff --fix ./app ./tests ./scripts
poetry run sqlfluff lint -v --disable-progress-bar ./app/queries.sql
